### ISSUE TITLE
Duplicated labels for Deployment

### ISSUE THREAD

**Issue by peterrosell** [EnterpriseDB/edb-postgres-for-kubernetes-charts#79]
I discovered when generating the resources via `helm template` and then applying them to Kubernetes via kustomize and ArgoCD I get an error that complains about duplicated labels on the deployment. It's the template of the deployment that gets duplicated `app.kubernetes.io/name: cloud-native-postgresql` labels.
The source is coming from this line
https://github.com/EnterpriseDB/cloud-native-postgresql-helm/blob/main/charts/cloud-native-postgresql/templates/deployment.yaml#L38

That label is also included in the `cloud-native-postgresql.selectorLabels` defined here, https://github.com/EnterpriseDB/cloud-native-postgresql-helm/blob/main/charts/cloud-native-postgresql/templates/_helpers.tpl#L49

So the solution is to remove that label from the deployment template and just use the labels from `selectorLabels`.

**Comment by NiccoloFei** [comment]
Closing since #80 has been merged
