### ISSUE TITLE
404 not found: operator repository

### ISSUE THREAD

**Issue by senyahnoj** [EnterpriseDB/edb-postgres-for-kubernetes-charts#92]
Following the documentation in the README, I'm getting 404 not found when trying to add the cloud native postgresql operator as a helm repository

```
helm repo add cnp https://enterprisedb.github.io/cloud-native-postgresql-helm
```

Getting the following error. Has the repository been removed?

```
Error: looks like "https://enterprisedb.github.io/cloud-native-postgresql-helm" is not a valid chart repository or cannot be reached: failed to fetch https://enterprisedb.github.io/cloud-native-postgresql-helm/index.yaml : 404 Not Found
```

**Comment by NiccoloFei** [comment]
The helm repository has been renamed, check out https://enterprisedb.github.io/edb-postgres-for-kubernetes-charts for the up to date instructions.
